build:
  verbosity: detailed

skip_commits:
  message: /\[ci skip\]/

platform:
- x64

image:
 - Visual Studio 2017

configuration:
 - Debug

environment:
  matrix:
  - COMPILER: clang-cl
  - COMPILER: cl

cache:
  - c:\projects\deps -> .appveyor.yml

install:
  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip"
  - set SFML_URL="https://www.sfml-dev.org/files/SFML-2.5.1-windows-vc15-64-bit.zip"
  - set DEPS_DIR=C:\projects\deps

  - if not exist %DEPS_DIR% (
      mkdir %DEPS_DIR% &&
      cd %DEPS_DIR% &&
      appveyor DownloadFile %NINJA_URL% -FileName ninja.zip &&
      appveyor DownloadFile %SFML_URL% -FileName sfml.zip &&
      7z x ninja.zip -o%DEPS_DIR%\ninja > nul &&
      7z x sfml.zip -o%DEPS_DIR%\sfml > nul)

  - set BOOST_ROOT=C:\Libraries\boost_1_69_0
  - set SFML_ROOT=%DEPS_DIR%\sfml\SFML-2.5.1
  - set SFML_BIN=%SFML_DIR%\bin
  - set NINJA_BIN=%DEPS_DIR%\ninja

  - set PATH=%NINJA_BIN%;%PATH%
  - set PATH=%SFML_BIN%;%PATH%

  - ninja --version
  - clang-cl -v

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule init
  - git submodule update

build_script:
  - cmake -Bbuild -GNinja -Wno-dev
          -DCMAKE_BUILD_TYPE=%configuration%
          -DCMAKE_CXX_COMPILER=%COMPILER%
          -DCMAKE_C_COMPILER=%COMPILER%
          -DBUILD_SHARED_LIBS:BOOL=OFF

  - cmake --build build

test_script:
  - ps: |
      & ctest -V -j nproc
