os: Visual Studio 2017

build:
  verbosity: detailed

skip_commits:
  message: /\[ci skip\]/
  # files:
  #   - README.md
  #   - .gitignore
  #   - .clang-tidy
  #   - .clang-format
  #   - docs/

environment:
  matrix:
  - Build: bomberman
    Configuration: Debug

cache:
  - c:\projects\deps -> .appveyor.yml
  
platform:
- x64

install:
  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-win.zip"
  - set SFML_URL="https://www.sfml-dev.org/files/SFML-2.4.2-windows-vc14-64-bit.zip"
  - set DEPS_DIR=C:\projects\deps

  - if not exist %DEPS_DIR% (
      mkdir %DEPS_DIR% &&
      cd %DEPS_DIR% &&
      appveyor DownloadFile %NINJA_URL% -FileName ninja.zip &&
      appveyor DownloadFile %SFML_URL% -FileName sfml.zip &&
      7z x ninja.zip -o%DEPS_DIR%\ninja > nul &&
      7z x sfml.zip -o%DEPS_DIR%\sfml > nul)

  - set BOOST_LIB=C:\Libraries\boost_1_65_1
  - set SFML_DIR=%DEPS_DIR%\sfml\SFML-2.4.2
  - set SFML_LIB=%SFML_DIR%\lib
  - set SFML_BIN=%SFML_DIR%\bin
  - set NINJA_BIN=%DEPS_DIR%\ninja
  - set LLVM_BIN="C:\Program Files\LLVM\bin"

  - set PATH=%NINJA_BIN%;%PATH%
  - set PATH=%SFML_BIN%;%PATH%
  - set PATH=%LLVM_BIN%;%PATH%
  - set INCLUDE=%INCLUDE%;%BOOST_LIB%
  - set LIB=%LIB%;%BOOST_LIB%;%SFML_LIB%

  - dir C:\
  - dir C:\Tools
  - dir C:\Libraries\
  - dir C:\Libraries\boost_1_64_0
  - dir C:\Libraries\boost_1_65_1
  - dir C:\Libraries\llvm-4.0.0
  - dir C:\Libraries\llvm-5.0.0
  - dir "C:\Program Files"
  - dir "C:\Program Files\LLVM"
  - dir "C:\Program Files\LLVM\bin"
  - dir "C:\Program Files (x86)"
  - ninja --version
  - clang-cl -v

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule init
  - git submodule update

build_script:
  - mkdir build
  - cd build
  - cmake .. -GNinja -DCMAKE_BUILD_TYPE=%Configuration%
                     -DCMAKE_CXX_COMPILER=clang-cl
                     -DCMAKE_C_COMPILER=clang-cl
                     -DCMAKE_LINKER=lld
                     -DBUILD_SHARED_LIBS:BOOL=OFF
  - cmake --build .

test_script:
  - ps: |
      & ctest -V -j nproc


