os: Visual Studio 2017

build:
  verbosity: detailed

environment:
  matrix:
  - Build: bomberman
    Configuration: Debug
  
platform:
- x64

install:
  # All external dependencies are installed in C:\projects\deps
  - mkdir C:\projects\deps
  - cd C:\projects\deps

  # Install Ninja
  # - IF NOT EXIST C:\projects\ninja (
  
  #     )
  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-win.zip"
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:\projects\deps\ninja > nul
  - set PATH=C:\projects\deps\ninja;%PATH%
  - ninja --version

  # Instal SFML
  # - IF NOT EXIST C:\projects\sfml (
  - set SFML_URL="https://www.sfml-dev.org/files/SFML-2.4.2-windows-vc14-64-bit.zip"
  - appveyor DownloadFile %SFML_URL% -FileName sfml.zip
  - 7z x sfml.zip -oC:\projects\deps\sfml > nul
  - set PATH=C:\projects\deps\sfml\SFML-2.4.2\bin;%PATH%
  - ls -al C:\projects\deps\sfml\SFML-2.4.2\bin

  # Setup the path to Clang-cl
  - set PATH="C:\Program Files\LLVM\bin";%PATH%
  - ls -al "C:\Program Files\LLVM\bin"
  - clang -v
  - clang-cl -v

  # Setup the path to Boost
  - set INCLUDE=%INCLUDE%;C:\Libraries\boost_1_63_0
  - set LIB=%LIB%;C:\Libraries\boost_1_63_0

before_build:
  - ls -l "C:\Program Files (x86)"
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule init
  - git submodule update

build_script:
  - mkdir build
  - cd build
  - cmake .. -GNinja -DCMAKE_BUILD_TYPE=%Configuration% -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DBUILD_SHARED_LIBS:BOOL=OFF
  - cmake --build .

test_script:
  - ps: |
      & ctest -V


